---
- name: Deploy Docker Application
  hosts: almalinux
  become: yes

  vars:
    git_repo: https://github.com/BaisakKG/AnsiblePB-DockerC-Nginx-PHP-MySql.git
    docker_compose_file: docker-compose.yml
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update system packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      
    - name: Install git and docker-ce
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - docker-ce

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Clone git repository
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: /opt/webapp
        single_branch: yes
        version: main

    - name: Run `docker-compose up`
      community.docker.docker_compose_v2:
        project_src: /opt/webapp/
      register: output

    - name: Verify that webapp services are running
      ansible.builtin.assert:
        that:
            - php_container.State == 'running'
            - db_container.State == 'running'
            - nginx_container.State == 'running'
        
      vars:
        php_container: >-
          {{ output.containers | selectattr("Service", "equalto", "php") | first }}
        db_container: >-
          {{ output.containers | selectattr("Service", "equalto", "db") | first }}
        nginx_container: >-
          {{ output.containers | selectattr("Service", "equalto", "nginx") | first }}